### ISSUE TITLE
Unable to launch /private/.../ppsideloader.app

### ISSUE THREAD

**Issue by StefanMeGit** [eni9889/ppsideloader#176]
every time i try to sideload Snapchat++, i got at the end the message "Unable to launch /private/.../ppsideloader.app" (he already copied the Snapchat++ but it crashes)

has anyone a idea whats the problem?

**Comment by avielc** [comment]
probably one of the dylib registered failed.
try to check the log on through xcode (there is a view log on device) which tells you why every app failed.
usually the issue would be because of an extra link path the app is looking for which is /jailbreak at the end (no idea how did that happen through sideload) 
but if you do some steps manually you'll get it up and runing

**Comment by r4m1live** [comment]
same problem no update at now

**Comment by mycoolbrah** [comment]
iv just had this happen to me today, sideloaded on xcode 8, ios 10.0, snapchat 9.39 for almost 3 months, and now today out of no where this error is occuring. no idea how to fix it 

Error 1: 

`SIGNING: *.dylib
/Users/michael/Library/Developer/Xcode/DerivedData/ppsideloader-gcocnvlnfrxbujebukkqoujryydy/Build/Products/Debug-iphoneos/ppsideloader.app/*.dylib: No such file or directory
`

Error 2:
`IGNING: FINAL BINARY WITH FE19A571847290F5EEAFBA5D144AF639722E166C ENTITLEMENTS: /Users/michael/Desktop/ppsideloader-master 10.11.32 PM/temp/app.entitlements
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure`
