### ISSUE TITLE
Snapchat ++ not working

### ISSUE THREAD

**Issue by XKJA** [eni9889/ppsideloader#221]
I tried every single method and new and old versions and none of them really worked like before,. i even tried the 9.43.0 version of the sign in and the ++ tweak. can someone help please...?

**Comment by Legitgamer264** [comment]
Snapchat just updated to 9.43.1. You would need the 9,43.1 sign in IPA

**Comment by ochitsuita** [comment]
where do i find the sign in IPA?

**Comment by beBoss** [comment]
9.43.1 doesn't work too, shows that it can't connect and to check ur internet connection...

**Comment by fa666ot** [comment]
i need help tooooooo

**Comment by XKJA** [comment]
bumpp., everyone is asking the same thing

**Comment by Legitgamer264** [comment]
Install and sign in with this 9.43.2 sign in IPA  [link](https://mega.nz/#!HgQ2UZaT!_jDGKyPxZ_Eq47lM4xCvOGl5EsOXtaVyPBcN5fexUic)
Then kill the app and install this [Snapchat++ IPA] (https://mega.nz/#!m0ZVlbpZ!mu633eBhfc5AdoAi4SoT3RBJ24WNS5zjU4j2cFqloOY) it should overwrite the sign in IPA because the bundle IDs are the same and you should still be logged into the app. I just did these steps and it's working. Whether you will get banned I'm not 100% sure. I haven't been banned yet

**Comment by fa666ot** [comment]
@Legitgamer264 what do you mean exactly by "then kill the app" ??? sorry im slow af LOL

**Comment by Legitgamer264** [comment]
@fa66otbBy kill the app I mean once you sign in, double tap the home button, find the snapchat screen and swipe it up. That kills the app. I'm on iOS 10.2 developer beta 3

**Comment by fa666ot** [comment]
@Legitgamer264 OHHHH okay hahaha i just never heard of the term "kill" being used to close an app my bad, but ima try this out now and let yous know if it worked for me or not!

**Comment by fa666ot** [comment]
@Legitgamer264 IT FUCKEN WORKSSSSS :D !!! THANKS MAN, UR A LIFE SAVERRRRR!!

**Comment by Legitgamer264** [comment]
@fa666ot you're welcome

**Comment by ae88** [comment]
@legitgamer264 I tried to login using the first link but still no luck.... it says could not log in some connection error

**Comment by ae88** [comment]
You put the sign in IPA the same way right? Just change its name to app.ipa and put it in ppsideloader folder. Is that correct?

**Comment by Legitgamer264** [comment]
That's most likely because snapchat updated to 9.44.0. You need the latest sign in IPA. I asked protechzone about it, I will link you when he updates it

**Comment by beBoss** [comment]
Why don't they tell us how to crack it or what snapchat detects in the versions and everybody can use it their own, and would be hard for snapchat to ban every version.. It is obvious that cracked versions work for a day or two and then they don't so there is a way cracked ones to work, and everybody to use its own version...

**Comment by Legitgamer264** [comment]
@beBoss cracking is harder than it looks. Do you know how to use Interactive Dissembler? Do you know how to reverse engineer a IPA file? Or any file for that matter? I don't think you do. So go ahead, try to do it yourself. You won't get very far if you don't know what to look for. It's harder than people think. I guarantee if you open the snapchat IPA in IDA or Hopper you won't know what to do. For someone to explain what to do would be hard because snapchat changes things every update. I checked myself. The offsets and methods change in every update and they are all in a different place. So it's not a straightforward thing to do

**Comment by beBoss** [comment]
Okay, then when you know what have cracked in the version before and know something about changes offsets and blabla, just tell me what they detect in the cracked version and block it. I would crack it for myself. For me it's obvious that the cracked version somehow looks like the original, and the proof is that it works until they blocked it or blocked something in it, so that's what I am looking for. Is there a forum or place that can be found an info or someone can share info how they crack it or just some advice if they are selfish crackers and don't share with others in 21st century. I am asking because I think there is a better and faster way to crack every version and to have different versions if one is blocked, and to not have need to wait for next snapchat release to see a new cracked version which will works for a day. That's it. And I haven't used mac disassembler, but I have experience in reversing under windows with ollydbg, x64dbg, IDA and etc, so please don't tell me what you think when you don't know me. Btw the comment it's not personal, and do not intend to annoy someone and or you, just want to help for myself or the other ppl out there who wants to use it, that's it. If I can help with something I will do it. And we are in github, the idea behind it everything to be shared, and help each other - open source. So again If anyone know something that can help would be nice if share it with use, for example you @Legitgamer264 who obviously know something or just trying to impress us, and you throw dust in the eyes? Anyway, all of you should got the point of my comments above and this one.

**Comment by ae88** [comment]
@legitgamer264 Ok please send me the link ASAP I only need the sign in one.... and I heard that version 9.38.0. Works really well, has anyone tried it or has the link for it?

Thank, I appreciate your fast response ❤️

**Comment by Legitgamer264** [comment]
The snapchat IPA and all of the App Store app iPAs are encrypted so people can't just look at them easily and poof you can see what was changed,etc. I don't crack apps and I have no desire to try. I just know a bit about how it works through a friend who reverse engineers software for a living to find security flaws. There is a reason the devs of tweaks don't know how snapchat is banning people or how to fix the connection error, it's because it's very very hard to see what was fixed and how to fix it because it's impossible to get the raw source code of any app. If it was so easy, then we would have a fix for the bans, etc. but it's hard to see what was changed. In IDA there are strings that then go to offsets. IDA and any other program can't show you the raw code that goes with a string or offset due to it being heavily encrypted. So as I said, no one knows for sure what was changed. People can make guesses, but it's near impossible to know for sure. I'm not trying to come off as someone who knows everything, which I don't. I just know a little about how IDA works and what it can and can't do. And what something being encrypted means and how hard it is to know for fact was changed. You can look at strings and offsets all you want, unless you don't know programming, like me, you won't know what you are looking at. It takes a lot of work and knowledge to know what you are looking at and how to possibly fix it. I didn't mean to come across as an asshole

**Comment by beBoss** [comment]
Yeah, yeah... Well, ipa files are encrypted and they can be easily decrypted, just thought you know something more about it, anyway, will check the snapchat on myself. I hope someone knows something and could give me a starting point not just to start digging from the beginning. Thanks for the info btw. If something comes up please inform us here or in pm, u know sharing is good for everyone :)

**Comment by Legitgamer264** [comment]
I will share when I find something useful. I am honestly interested on how they make a sign in IPA. I have an idea on what to try. I think I can open two files in IDA then I can have it compare both files (a sign in one compared to the stock app) I'm not sure, I'm in school at the moment

**Comment by Legitgamer264** [comment]
It won't work because from what I've heard, you have to have some version that's on the latest snapchat version. So right now it's 9.44.0. But when protechzone updates the sign in to 9.44.0, I will link you. You need the sign in because you can't overwrite a stock app with another version. That's why people need sign in apps to mimic the stock one, but with sign in iPAs you can overwrite them when with the stock app, you can't

**Comment by Legitgamer264** [comment]
Here is the 9.44.0 Sign In IPA. Give it a try with the whole overwrite workaround for getting it to work
https://mega.nz/#!tE8E2KRA!fXyBU6IzxmXvJvvhrEfWpem2YuHmFXH9L0-9uSi5VR8

**Comment by beBoss** [comment]
What's the right method to try this, could you explain it with two-three steps?

**Comment by Legitgamer264** [comment]
sure. Using impactor - Sign into that sign in IPA I linked. then kill the app by double tapping the home button then swiping the app up, that in a sense "kills it". Then download this the Snapchat++ 9.38.0 IPA
https://mega.nz/#!ANcSwApS!8mfJLjidVe5YbDrVfOIEW8hN7XfiR2bk0fGPQTCyFVM
Then install that ^^ through impactor and the ++ should overwrite the Sign in and keep you signed in. So you should have the ++ snapchat installed over the 9.44.0 sign in

**Comment by beBoss** [comment]
Ahh it's a big mess with this sign, sign into blabla, can't understand you when mean to login or sign the app with dev signature. So I am still guessing the method, you tell me if it's right

1. Using impactor I have to "LOG IN" in this app:
https://mega.nz/#!tE8E2KRA!fXyBU6IzxmXvJvvhrEfWpem2YuHmFXH9L0-9uSi5VR8

2. Kill the app

3. Download the 3.38 from here:
https://mega.nz/#!ANcSwApS!8mfJLjidVe5YbDrVfOIEW8hN7XfiR2bk0fGPQTCyFVM

4. Install and run and should work, cuz will use the 9.44 saved session

**Comment by Legitgamer264** [comment]
Correct

**Comment by beBoss** [comment]
Well Windows version of cydia impactor doesn't work, will try after 10 min with mac version.
btw should I use cydia impactor or I can use xcode and my dev account, ppsideloader and to sign the app myself?

**Comment by Legitgamer264** [comment]
Why won't the windows one work?

**Comment by beBoss** [comment]
Shows me this error:
https://s17.postimg.org/f119y0udr/impactor_error.png

Doesn't detect my iPhone? It's connected and works for sure! And yeah it's allowed to my PC.

**Comment by Legitgamer264** [comment]
You may need to clean uninstall iTunes and reinstall it. I had that issue before. It was connected, etc. my windows computer wouldn't recognize it. But it may work on your Mac

**Comment by beBoss** [comment]
Well I am updating iturens hope will update the driver if not I am going to give a try in MAC. But anyway, what about xcode and ppsideloader? Will do the same thing, right?

**Comment by Legitgamer264** [comment]
Ppsideloader Xcode project just takes the ++ along with the latest app IPA that you download and makes it into an IPA. Xcode may work if your Mac recognizes your iPhone

**Comment by beBoss** [comment]
Yeah mac works don't worry. I used Xcode and sign the apps with my dev account, but both apps are working, so what's the point to use this method? Or the first app .44 will stop working and the idea is to have working latest app just to get the session and then to use not banned older version? Is that the story here?

**Comment by ae88** [comment]
Thanks, it worked! But isnt their a way to do it on the latest snapchat version or a newer version?

**Comment by ae88** [comment]
And i cannot save snaps with this one 😟

**Comment by ae88** [comment]
after logging in with the link my man @legitgamer264 provided https://mega.nz/#!ANcSwApS!8mfJLjidVe5YbDrVfOIEW8hN7XfiR2bk0fGPQTCyFVM
over write the app with this link 
http://www.filepup.net/files/WBNZyD1472682523.html
and everything should work fine (including saving snaps) because previously it didn't work

**Comment by Legitgamer264** [comment]
I just saw on Discord that 9.38++ if I'm not mistaken, is no longer supported. Just so you all know if you try and use it and it doesn't work

**Comment by Legitgamer264** [comment]
are there any working versions of snapchat++ hat will allow you to save Stories? the 9.38.0 one won't allow the saving of stories

**Comment by ae88** [comment]
@legitgamer264 it does work and it does save stories!

**Comment by s2ri** [comment]
@Legitgamer264 is that work with phantom ?

**Comment by Legitgamer264** [comment]
@sr2 what works with phantom?

**Comment by Nameless2b** [comment]
Why the version 9.38.0 don't have the save snap please ? Currently I am ban on Snapchat with 9.32.2 version.

**Comment by Nameless2b** [comment]
9.37.2 sorry.

**Comment by beBoss** [comment]
It has...

**Comment by Nameless2b** [comment]
Is it normal that I get banned with SnapChat++ 9.37.2 ? They tell me I'm using a pluging and they ban me 24hours.

**Comment by fa666ot** [comment]
@Legitgamer264 this fix doesnt seem to work anymore, still using the original files you posted but now after im logged in, i cant look at anything thats been sent to me or send anything to anyone and it says to refresh and it cant be connected, then it logs me out randomly

**Comment by Legitgamer264** [comment]
@fa666ot it looks like SC hacked app detection has gotten better. There may be a way around that, I will try it when I get home. Involves using https://www.reddit.com/r/jailbreak/comments/5hj2du/release_sac_updated_jailed_and_jailbroken/?st=IWJENOBL&sh=dfd105e9 the IPA in that thread

**Comment by Nameless2b** [comment]
Legitgamer264. Is it normal that I get banned with SnapChat++ 9.37.2 ? They tell me I'm using a plugin and they ban me 24hours.

**Comment by Nameless2b** [comment]
Now impossible to connect..

**Comment by fa666ot** [comment]
@Legitgamer264 just seeing this now but thank you!! ill try it out tomorrow and let you know if it works, did it endup working for you??

**Comment by fa666ot** [comment]
@Legitgamer264 also it seems theres no link for the IPA now btw, do you happen to have it??

**Comment by crisdavid7341** [comment]
I recently read that Snapchat was getting version number information whenever a user updated the app. Once they saw that the user device could run the latest version of Snapchat; they mark your account, and you can no longer downgrade to an older version of Snapchat. Had you not updated, or had auto update for the official Snapchat you wouldn't have been affected(for those who were using the notification workaround, or had the official app laying around). I believe this is another reason people cannot successfully use this side loading method. They're cracking down hard on anything that is not apart of the official Snapchat application.

**Comment by carsoso101** [comment]
snapchat ++ won't download into my phone i did what it told me to do but it's saying "build failed" and it is because of the ppsideloader. What do I do?
