### ISSUE TITLE
is there any solution for facebook++ crashing after build

### ISSUE THREAD

**Issue by sinfulslave** [eni9889/ppsideloader#224]
i tried using xcode 8 and used virtual mac
and no use fb never opened with me it opens and closes automatically

**Comment by Legitgamer264** [comment]
I don't think the latest Facebook is compatible with the ++ tweak. The dev needs to update the ++ tweak so it's compatible

**Comment by sinfulslave** [comment]
it is version 68 and even i tried that on ios 9 be4 about 2 month ago or 3 it was the same problem

**Comment by crisdavid7341** [comment]
It not so much as your iOS version as it's more on the Facebook ap. To me I think it might be because they shifted the app to solely 64 bit on the new versions. On jailbreak its recommended to download the older version of Facebook in order to get some of the tweaks in ++ like messaging from the Facebook app before they moved to Messenger.
