### ISSUE TITLE
how to build IPA file

### ISSUE THREAD

**Issue by Muath1412** [eni9889/ppsideloader#98]
I downloaded the tweaks on your page, but the files was like xxxxx.bundle. 
So how to build IPA file from them?
thank you.

**Comment by joeafflitto** [comment]
Download the tweak as a .zip file, unzip it, change the Snapchat IPA name to "app.ipa" and overwrite it into the unzipped folder, then open the .xcodeproj file and run it.

**Comment by Muath1412** [comment]
@joeafflitto if you download the tweaks from here https://github.com/eni9889/pptweaks
the files after unzip them is like XXXXXX.bundle not an IPA file.
and i need to make an IPA file of them first in order to install it.
I'm searching for a way in google but no luck :(

**Comment by Muath1412** [comment]
Also in ppsideloader folder there is a folder named "script" which contain a file named make_ipa and i know it has to be it, but the i don't know the way to do it.

**Comment by joeafflitto** [comment]
https://github.com/eni9889/ppsideloader

download that as a .zip and unzip it. It'll create a pp-master folder or something like that (not home, can't see it myself right now). There'll be a "app.ipa" file in that folder. Delete it. Go to iPhoneCake website to download the snapchat IPA, rename it "app.ipa" and put it in the folder. After that, open the Xcode project file in the Xcode app.

**Comment by joeafflitto** [comment]
To clarify, are you just trying to build the cracked IPA or are you trying to run it strait to a device?

**Comment by Muath1412** [comment]
@joeafflitto Build the cracked IPA from here https://github.com/eni9889/pptweaks.
have you tried to download the tweaks from https://github.com/eni9889/pptweaks? 
thanks so much for helping!

**Comment by joeafflitto** [comment]
I haven't tried it, I'll try to figure it out for you, but I'm pretty sure I know how you can build the IPA with the other project too if you don't need this one specifically.

**Comment by Muath1412** [comment]
@joeafflitto I have been searching for a way in a while, but no luck. So please if you find a way share it with me. 
Thanks

**Comment by crisdavid7341** [comment]
Is there a way to obtain the watch app for the cracked app as well?

**Comment by Jaff22** [comment]
Completely forgot about your thread bro, tell me if you are still searching. @crisdavid7341 this sideloader supports only select iPhone apps.

**Comment by saud978** [comment]
To build the cracked IPA file of the app just change the "CREATE_IPA_FILES" option to YES in PP_SIDELOADER_OPTIONS.plist from inside the Xcode project of ppsideloader 
Hope this helps

**Comment by crisdavid7341** [comment]
I'm not seeing the IPA in a product folder;but the app gets built and runs successful on my phone.

**Comment by avielc** [comment]
@Jaff22 any possible way to manually direct the download and extraction of a tweak?
i want to change the path to cydia.online which has a later updates of a certain tweak

**Comment by Jaff22** [comment]
@avielc not sure I understand the question. Are you jailbroken or not?

**Comment by avielc** [comment]
@Jaff22 Hi man,
no, I'm not Jbed, but i'm using the sideloader here to modify the IPA and use xcode, etc..
problem is the sideloader pulls version 1.4r28 (of the tweak) and not anything newers.
but i've managed to find a source i can download the latest tweak, and was hoping i could get some directions on how to add it manually to the app, understand my idea?

**Comment by Jaff22** [comment]
@avielc Not really sure if there's a way to do that, but if you download the debian file and change the extension from .deb to .zip and extract it you may be able to find it... I'll try to figure it out when I get home later, I doubt it will work though. I recommend you jailbreak your device and download it through Cydia, you'll get alerts when there's an update available and you wont need to reload every 7 days.

**Comment by avielc** [comment]
@Jaff22 
you're right about the jailbreak process, but i'm afraid i can't as i'm on ios10beta (and quite enjoying it so far, but i might switch over (to the dark side) after a jb will come out for ios10 

regarding the changing the extension, 7zip deals with it no problem.
my only issue is how to build the final IPA with a deb and IPA file. (i need to find a way to modify unlimapps script and build it up using his script.

**Comment by kmddd59** [comment]
i can send a deb I’m jailbroken if you want ill send it let me know

**Comment by avielc** [comment]
I can download the deb myself @kmddd59 Thanks for the offer.
What i really need is understanding how do i add the files inside the deb into the IPA properly (i assume after that i need to sign and send it to the iphone. but that's suppose to be known by now. (ios app signer, xcode, etc.

**Comment by Jaff22** [comment]
Gotta be honest when I say this is the first thread I'm completely mind boggled by. I'll keep trying but I can't think of any ways to do it without just using Cydia.

**Comment by avielc** [comment]
hahaha, @Jaff22 , buddy, its quite simple.
sideloading has been developed simply to help you download "tweaked" apps to a non-jailbroken iphone. that way you don't need to jail break it if you don't want to. (there is this whole dev procedure and a 7 days time limit etc, but that doesn't matter)
the thing is, sideloader, the script we are discussing in one of its issues is doing exactly that.
it takes an IPA (a decrypted one) and adds into it a deb\dylib files from an online repository to turn a simple app into a tweaked one.

What i'm trying to do, is simply change where will it try to take the deb\dylib from. that's all (and if its possible to begin with)

simple :)

**Comment by Jaff22** [comment]
Well wouldn't that be in one of the scripts from inside the Xcode project?

**Comment by avielc** [comment]
it is, i actually found it, but i'm not sure how to modify it :)

**Comment by lilws** [comment]
I didn't find this topic here, I found the script and modified it to stop download the pptweak.zip files and use the newest of poke go++ version, but there must be something wrong so it always patch the 1.4r-28. I don't know why this version still get inside even it stop download, stop unzip, I created the working_dir itself and put the newest dylib inside. I'm finding a way to debug every step to find out which step is wrong.

**Comment by avielc** [comment]
Ive managed to alter the script to pull the tweak elsewhere, but i'm unable to to make it work, once i do that using the cydia.online file the app crashes, so i'm probably missing something else.
question is what.

**Comment by lilws** [comment]
I think I come very close now, I got optool and install_name_tool which help a lot. The app crashed because in JB version all libraries is located in /usr/lib/. But in non-JB it is store in @executable_path/. It did running now but crashed because of something else and I can't figure out atm.

**Comment by avielc** [comment]
Care to share? if we can reverse engineer a working ipa, it could help, no?

**Comment by lilws** [comment]
First, you will need get off otool-classic (I found one online with name optool but this one is ok) and install_name_tool from Xcode/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/

then go to this site and work for things like libuasharexxx:
http://thecourtsofchaos.com/2013/09/16/how-to-copy-and-relink-binaries-on-osx/

you will need to change all those thing to @executable_path/[libname]
I found there is path of CydiaSubstrate too but I can't delete the path because it requires RC-path something I don't know. But then I change the path to the @executable_path/CydiaSubstrate (you will need to find it and of course modify the code in modify_app in the project to sign.

you will need to stop modify_app to download,unzip, delete folder of working_dir, add make_ipa to the project too and stop it to delete the working_dir folder too. Then put all the needed libraries into working_dir and build the project.

p/s: sorry for buggy explanation. I need to figure things out before document this one.

**Comment by avielc** [comment]
the otool was given out in the first version of pokemonanywhere, so that part is ok.
regarding the other, not sure how its related.
to make it a little more clear.
You can use one of the modified IPA's just to add what you need.
let's try to work out from there. What do you need to actually run to make things catch on?
From what I understand, the main issue here, is somehow to link the tweak into the IPA, and that's probably what you mean with "change the path to the @executable_path etc.." which i'm pondering how (will look up the link now)

sorry for the late reply, been having the window open all day and haven't be able to finish typing it :) (always had something come up so i had to get up)

**Comment by lilws** [comment]
you should run "otool -L pptweak.dylib" pptweak.dylib is the pokego++ 1.5r_7. you will see a list of path that some of them contains path to dylib. when you run ppsideloader and install to your iOS, it crashed and thrown an error in the debug window. it might say "dyld:  path/to/library/ file not found" that is where we will need to correct the library (dylib) path file.

for example the app crashed when it can't find the path to /usr/lib/libuasharetools.dylib. Because it is non-JB so it can't access to that path on iOS, instead we have those dylib inside Payload/app.ipa/*.dylib. This path is where it would say "@executable_path/*.dylib".

You can run otool to compare the pptweak.dylib in the latest version that is posting somewhere on youtube with the pptweak.dylib you download in cydia. It is a huge different inside there.

I'm sorry can't explain further more right now because last night my SSD running low and I tried to add more space cause the crashing of all MAC OS X. Now I reinstalled and download xcode to start again. pain in the A$$.

**Comment by kmddd59** [comment]
i can resign ipa files i got a dev account can you please send the ipa to me I’m wanting this or send me a link to the project you can send it to me on twitter @wtfarris or my email kmdu58@icloud.com

**Comment by lilws** [comment]
@kmddd59 
you can always go to @miniroo321 's twitter and download it.

**Comment by avielc** [comment]
@lilws @kmddd59 
Thanks for all the info man! that's pretty awesome!
I'll start with the biggest issue of all.
When i compare the size of the pptweak.dylib from the working IPA published on the youtube vid, its different in size from the one i download from cydia. do you think the otool is overcoming this issue?

@kmddd59 Thanks for the assistance with signing, i don't mind signing it myself, the biggest issue is actually compiling it all together.

**Comment by Jaff22** [comment]
@avielc do you mean the .deb file you would download from Cydia? That's a .zip file renamed, it's compressed.

**Comment by avielc** [comment]
@Jaff22 I know mate, inside the .deb you have two files, .plist of the tweak and .dylib, the actual file size is different from the one found inside a "ready-to-use" IPA. 
so i wonder if its because otool does some changes to the dylib itself or not. (maybe our issue is with the actual source of the file and not the procedure.

**Comment by avielc** [comment]
@Jaff22 @lilws @kmddd59 
From what i can tell its all the same both otool results from a file off cydia and a file from inside the ipa, both return the same paths.

**Comment by lilws** [comment]
@avielc from what I came so far the different is in the code itself. We are not owner of the library so we can’t combine anything for that. And change the path does not solve any problem yet. In pptweak.deb, it has only 2 path for libuasharetools.dylib which present for 32 bit and 64 bit architecture. So basically the file from cydia won’t help us must anyway. Because it has 4 path in each architecture, it means 8 path. Change the path does not solve the code itself. So we will need to get off the other 6 path of code which mean a lot of code inside the library there. If you want to test. You can change all the path to one uashare library. It will throw error about some code exception is calling but not compatible. It means each library have their own code inside pptweak. If you can hack and do the low level programing, you can do something else for this. Now it likes I’m burry myself in these problems. I think i can’t help anymore.

**Comment by avielc** [comment]
@lilws That's ok, I appreciate all the help so far, it looks like @eni9889 has done an extra work to get the integration between the tweak to sideloading. (i can't think of anything else there.)

So thanks again guys. all that's left is to wait for news then

**Comment by crisdavid7341** [comment]
Not sure if you guys saw this but I've seen that some of you were trying to grab the cydia version. While I don't have a solution you can check what the version is used when you sideload here
https://github.com/eni9889/pptweaks

**Comment by avielc** [comment]
Thanks. Buddy I've been following it on a daily basis now as it is the only way to get/know when a tweak is available. 
Building a tweak for the side load is a mystery still

**Comment by lilws** [comment]
@avielc I knew the pptweaks and see it is seldom update, but guess what I found? Yesterday I contact the owner twitter and request for the update, he has just updated the new version couple hours ago. I don't know why I should be that stupid that I forget to poke the owner.

**Comment by avielc** [comment]
Trust me mate, i poked him so many times he should look like a Swiss cheese by now..
but glad you also poked him, I also did that and noticed he started updating the tweak repo again.
now i gotta update it (and looks like i need to do it manually, because it just won't work using his project..) for some odd reasons.

**Comment by lilws** [comment]
Oh, I didn't know you did that too. I just need to download the zip and extract to the working_dir, modified some codes there so it will be fine. The download code inside his project got some problems in recognize the ID, I guess so.

**Comment by avielc** [comment]
yea,
the simplest solution is as you said, download the zip and extract it inside the IPA, all you need after that is run his "insert dylib" part of the script as is on the executable file and compress everything back to IPA and sign it.

**Comment by r4m1live** [comment]
I think its problem with snapchat also insta++ its all time crash ..if i use pptweaks its work well?! Or same problems 

Im tired to make it :(
